### PR TITLE
Add 'Content-Length: 0' header on multipart upload creation

### PR DESCRIPTION
**Pull request by thundergolfer**
*Issue #:* https://github.com/awslabs/mountpoint-s3/issues/853

*Description of changes:*

As is done by the other methods (using `aws_s3_message_util_assign_body`) set the 'Content-Length' header on multi-part upload creation. Google Cloud Storage requires this header to be present, and [AWS will accept it. ](https://github.com/awslabs/mountpoint-s3/issues/853#issuecomment-2061607251)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by thundergolfer** [comment]
@waahm7 would you be able to look at this? 🙂

**Comment by waahm7** [comment]
@thundergolfer Thank you for creating the issue. Sure, I will take a look and let you know as soon as I have any updates.

**Comment by thundergolfer** [comment]
@waahm7 friendly bump on this. just for planning on our side, what's the rough estimate on how soon this can be merged? 🙂

**Comment by waahm7** [comment]
@thundergolfer Sorry, I have been busy with other stuff and haven't had the chance to look into this yet. It's on the list of things that I am currently looking into. If Content-Length header is the only thing missing, we should be able to get it merged by the end of the week in the best case or end of next week.

**Comment by thundergolfer** [comment]
Thanks for the update 🙏

**Review by waahm7 — APPROVED** [review]

**Comment by waahm7** [comment]
Thank you for your contribution. It LGTM but the CI is failing. I have created a duplicate PR #428 to fix the CI.

**Comment by thundergolfer** [comment]
Thanks!

**Comment by waahm7** [comment]
@thundergolfer This fix is released in https://github.com/awslabs/aws-c-s3/releases/tag/v0.5.8

**Pull request closed without merging**
